### ISSUE TITLE
NRM Feature request: Per server setting

### ISSUE THREAD

**Issue by FearNaBoinne** [somebody1234/userscripts#3]
Would it be possible to have a per-server setting for NRM?

Most servers I want mentions off, but there's a few I'd like to keep them ON due to the amount of messages in the chats...

**Comment by somebody1234** [comment]
unfortunately that's... harder to do than expected, maybe you'll have luck looking around on the BD servers?

**Comment by somebody1234** [comment]
[bd has taken over maintenance](https://betterdiscord.app/plugin/NoReplyMention) so closing all issues related to nrm.
also note that this *is* meant to be a simple plugin; there seems to be [another one](https://betterdiscord.app/plugin/SuppressReplyMentions) with more features, might be worth a try asking there instead
