### ISSUE TITLE
[NRM Feature Request] Shift+Reply enable pings

### ISSUE THREAD

**Issue by ZombieZilla** [somebody1234/userscripts#4]
As NoReplyMention changes the default ping behaviour to be disabled, and shift+reply normally turns off pings, it makes sense for shift+reply to enable pings with this plugin.

**Comment by somebody1234** [comment]
very late, but:
- i'm not maintaining this any more (bd has essentially taken over what little there is to maintain anyway)
- it's meant to be a simple fix, so most feature requests are out of scope
  - that said, this one should be pretty easy, *but* i can't even get the new version to work so i'm afraid i can't help with this
