### ISSUE TITLE
Update needed for BD 1.7.0

### ISSUE THREAD

**Issue by tockity** [somebody1234/userscripts#5]
Thanks for this wonderful plugin, it's saved my sanity for the longest time. Unfortunately BD's most recent update appears to have broken everything, so all plugins need to be updated.

**Comment by SumOfAllN00bs** [comment]
seconded, NoReplyMention stopped working

**Comment by somebody1234** [comment]
note that you've been able to shift-click for the longest time - it's become a habit for me when i'm using browser discord...
(... and that i haven't really been using bd for the longest time)

but i'll see if there's something i can do anyway

**Comment by somebody1234** [comment]
worth noting that the current version uses `createPendingReply`; there doesn't seem to be *anything* (well, anything usful) containing `Reply` anymore. not sure how discord changed their apis, so not sure whether it'll still be very easy

**Comment by somebody1234** [comment]
there *is* [another plugin](https://betterdiscord.app/plugin/SuppressReplyMentions) that seems to have similar functionality, maybe that's an option?

**Comment by somebody1234** [comment]
ah, seems to have been fixed by bd themselves: [see the plugin page](https://betterdiscord.app/plugin/NoReplyMention).

for some reason it hasn't been updated even though the version has been bumped though, but that's something you'd probably want to ask in the bd server
